__author__ = "TriEyeMonster"
__copyright__ = "Copyright 2015"
__credits__ = [""]
__license__ = "BSD"
__version__ = "0.0.7"
__maintainer__ = "TriEyeMonster"
__email__ = "wguan17@gmail.com"
__status__ = "Development"
__url__ = 'https://github.com/TriEyeMonster/trading-ig'
